#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 22 20:50:55 2018

@author: guille
"""

import gym

# Enviroment parameters
env=gym.make('LunarLander-v2')
STATE_SIZE=env.observation_space.shape[0]
ACTION_SPACE=env.action_space.n
ACTION_SIZE=1

# Evaluator parameters:
EPISODES_TO_EVALUATE=20
EPOCHS_PER_EPISODE_TO_EVALUATE=500
VISUALIZE_EVALUATOR=True

# Learning parameters:
MINIBATCH_SIZE=32
LEARNING_RATE=1e-4 
TAU=1e-4
MEMORY_MAX_SIZE=1e6
L2_LAMBDA=1e-3
DISCOUNT_FACTOR=0.99

# Program parameters
NUM_EPISODES=100000
RENDER=False
EPISODE_CHECKPOINT=25
TIME_CHECKPOINT=100
WARMUP_EPISODES=500

LOGS_PATH="/tmp/lander_logs"
SAVE_PATH="/tmp/lander_weights"
INDEX_STATE=0
INDEX_REWARD=1
INDEX_DONE=2
INDEX_LAST_STATE=3
INDEX_ACTION=4
VAR_SIZE_DIC={INDEX_STATE:STATE_SIZE,
              INDEX_REWARD:1,
              INDEX_DONE:1,
              INDEX_LAST_STATE:STATE_SIZE,
              INDEX_ACTION:ACTION_SIZE}

# Net parameters
HIDDEN_UNITS=256

# Tuning parameters
TUNING=True
TUNING_ITERATIONS=25
TUNER_PATH="/tmp/lander_tuner.csv"
MIN_LEARNING_RATE=-5 #10^MIN_LEARNING_RATE
MAX_LEARNING_RATE=-1 #10^MAX_LEARNING_RATE
MINIBATCH_SIZE_LIST=[32,64,128,256,512,1024]
HIDDEN_UNITS_LIST=[32,64,128,256,512,1024]
MIN_TAU=-5 #10^MIN_TAU
MAX_TAU=-1 #10^MAX_TAU
MIN_L2_LAMBDA=-6 #10^MIN_L2_LAMBDA
MAX_L2_LAMBDA=-2 #10^MIN_L2_LAMBDA
MIN_LR_DECAY=0.5
MAX_LR_DECAY=0.1
